<%@ Page Title="" Language="C#" MasterPageFile="~/01_Master_Page/MasterPage_Admin.master" AutoEventWireup="true" CodeBehind="Manage_Professor.aspx.cs" Inherits="Project._02_Web_Page.Manage_Professor" %>

<asp:Content ID="Content1" ContentPlaceHolderID="navbar" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder" runat="server">

    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Project_Db %>"
        SelectCommand="SELECT * FROM [Adv_Pro]"
        UpdateCommand="UPDATE [Adv_Pro] SET [School_DP] = @School_DP, [Edu] = @Edu, [Exp] = @Exp, [Address] = @Address, [Phone_Num] = @Phone_Num, [Point] = @Point, [Point_Remain] = @Point_Remain WHERE [Name] = @Name"
        InsertCommand="INSERT INTO Adv_Pro(Name, School_Dp, Edu, Exp, Address, Phone_Num) VALUES (@Name, @School_DP, @Edu, @Exp, @Address, @Phone_Num)">
        <InsertParameters>
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="School_Dp" Type="String" />
            <asp:Parameter Name="Edu" Type="String" />
            <asp:Parameter Name="Exp" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="Phone_Num" Type="String" />
        </InsertParameters>
    </asp:SqlDataSource>

     <asp:DetailsView ID="DetailsView_Edit" runat="server" AutoGenerateRows="False" CellPadding="4" DataKeyNames="Name" DataSourceID="SqlDataSource1" ForeColor="Black" Height="252px" Width="550px" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellSpacing="2" CssClass="auto-style1">
        <EditRowStyle BackColor="White" Font-Bold="True" ForeColor="Black" />
        <Fields>
            <asp:BoundField DataField="Name" HeaderText="姓名" SortExpression="Name" />
            <asp:BoundField DataField="School_DP" HeaderText="單位" SortExpression="School_DP" />
            <asp:BoundField DataField="Edu" HeaderText="學歷" SortExpression="Edu" />
            <asp:BoundField DataField="Exp" HeaderText="經歷" ReadOnly="True" SortExpression="Exp" />
            <asp:BoundField DataField="Address" HeaderText="地址" SortExpression="Address" />
            <asp:BoundField DataField="Phone_Num" HeaderText="電話號碼" SortExpression="Phone_Num" />
            <asp:CommandField ShowEditButton="True" ShowInsertButton="True" />
        </Fields>
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
        <RowStyle BackColor="White" />
    </asp:DetailsView>

    <asp:GridView ID="GridView_List" runat="server" AllowSorting="True" DataKeyNames="Name" DataSourceID="SqlDataSource1" HorizontalAlign="Right" Width="100%" ForeColor="Black" AutoGenerateColumns="False" AllowPaging="True" PageSize="15" OnSelectedIndexChanged="GridView_List_SelectedIndexChanged" AutoGenerateSelectButton="True" AutoGenerateDeleteButton="True">
        <Columns>
            <asp:BoundField DataField="Name" HeaderText="姓名" SortExpression="Name" />
            <asp:BoundField DataField="School_DP" HeaderText="單位" SortExpression="School_DP" />
            <asp:BoundField DataField="Edu" HeaderText="學歷" SortExpression="Edu" />
            <asp:BoundField DataField="Exp" HeaderText="經歷" ReadOnly="True" SortExpression="Exp" />
            <asp:BoundField DataField="Address" HeaderText="地址" SortExpression="Address" />
            <asp:BoundField DataField="Phone_Num" HeaderText="電話號碼" SortExpression="Phone_Num" />
        </Columns>
    </asp:GridView>

</asp:Content>
