<%@ Page Title="" Language="C#" MasterPageFile="~/01_Administrator/AD_MasterPage.master" AutoEventWireup="true" CodeBehind="AD_Manage_Prof.aspx.cs" Inherits="Project._01_Administrator.AD_Manage_Prof" %>
<asp:Content ID="WebContent" ContentPlaceHolderID="WebContent" runat="server">

    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Project_Db %>"
        SelectCommand="SELECT * FROM [Adv_Pro]"
        UpdateCommand="UPDATE [Adv_Pro] SET [School_DP] = @School_DP, [Edu] = @Edu, [Exp] = @Exp, [Address] = @Address, [Phone_Num] = @Phone_Num, [Point] = @Point, [Point_Remain] = @Point_Remain WHERE [Name] = @Name"
        InsertCommand="INSERT INTO Adv_Pro(Name, School_Dp, Edu, Exp, Address, Phone_Num) VALUES (@Name, @School_DP, @Edu, @Exp, @Address, @Phone_Num)">
        <insertparameters>
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="School_Dp" Type="String" />
            <asp:Parameter Name="Edu" Type="String" />
            <asp:Parameter Name="Exp" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="Phone_Num" Type="String" />
        </insertparameters>
    </asp:SqlDataSource>

    <asp:DetailsView ID="DetailsView_Edit" runat="server" AutoGenerateRows="False" CellPadding="4" DataKeyNames="Name" DataSourceID="SqlDataSource1" ForeColor="Black" Height="252px" Width="550px" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellSpacing="2" CssClass="auto-style1">
        <editrowstyle backcolor="White" font-bold="True" forecolor="Black" />
        <fields>
            <asp:BoundField DataField="Name" HeaderText="姓名" SortExpression="Name" />
            <asp:BoundField DataField="School_DP" HeaderText="單位" SortExpression="School_DP" />
            <asp:BoundField DataField="Edu" HeaderText="學歷" SortExpression="Edu" />
            <asp:BoundField DataField="Exp" HeaderText="經歷" ReadOnly="True" SortExpression="Exp" />
            <asp:BoundField DataField="Address" HeaderText="地址" SortExpression="Address" />
            <asp:BoundField DataField="Phone_Num" HeaderText="電話號碼" SortExpression="Phone_Num" />
            <asp:CommandField ShowEditButton="True" ShowInsertButton="True" />
        </fields>
        <footerstyle backcolor="#CCCCCC" />
        <headerstyle backcolor="Black" font-bold="True" forecolor="White" />
        <pagerstyle backcolor="#CCCCCC" forecolor="Black" horizontalalign="Left" />
        <rowstyle backcolor="White" />
    </asp:DetailsView>

    <asp:GridView ID="GridView_List" runat="server" AllowSorting="True" DataKeyNames="Name" DataSourceID="SqlDataSource1" HorizontalAlign="Right" Width="100%" ForeColor="Black" AutoGenerateColumns="False" AllowPaging="True" PageSize="15" OnSelectedIndexChanged="GridView_List_SelectedIndexChanged" AutoGenerateSelectButton="True" AutoGenerateDeleteButton="True">
        <columns>
            <asp:BoundField DataField="Name" HeaderText="姓名" SortExpression="Name" />
            <asp:BoundField DataField="School_DP" HeaderText="單位" SortExpression="School_DP" />
            <asp:BoundField DataField="Edu" HeaderText="學歷" SortExpression="Edu" />
            <asp:BoundField DataField="Exp" HeaderText="經歷" ReadOnly="True" SortExpression="Exp" />
            <asp:BoundField DataField="Address" HeaderText="地址" SortExpression="Address" />
            <asp:BoundField DataField="Phone_Num" HeaderText="電話號碼" SortExpression="Phone_Num" />
        </columns>
    </asp:GridView>
</asp:Content>
